pipeline:
  name: release
  identifier: release
  tags: {}
  template:
    templateRef: semversvu
    versionLabel: Version1
    gitBranch: feat/improve-cicd-workflow
  projectIdentifier: default_project
  orgIdentifier: default
