pipeline:
  name: release
  identifier: release
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: pavankarnatigh
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Semver and Release
        identifier: semver_release
        template:
          templateRef: semversvu
          versionLabel: Version1
    - stage:
        name: deploy-staging
        identifier: deploystaging
        description: "Deploy semver-tagged image to staging namespace on minikube"
        type: Deployment
        when:
          pipelineStatus: Success
          condition: <+pipeline.stages.semver_release.spec.execution.steps.compute_next_version.output.outputVariables.NEXT_VERSION> != "SKIP"
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: springsamplestg
          environment:
            environmentRef: stgminikube
            deployToAll: false
            infrastructureDefinitions:
              - identifier: minikube
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    ignoreReleaseHistFailStatus: false
                    useUpgradeInstall: true
                    commandFlags:
                      - commandType: Upgrade
                        flag: "--set image.tag=<+pipeline.stages.semver_release.spec.execution.steps.compute_next_version.output.outputVariables.NEXT_VERSION> --set ingress.hosts[0].host=spring-app-stg.test"
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
