trigger:
  name: Main Merge Release Trigger
  identifier: MainMergeReleaseTrigger
  enabled: true
  encryptedWebhookSecretIdentifier: ""
  description: ""
  orgIdentifier: default
  stagesToExecute: []
  projectIdentifier: default_project
  pipelineIdentifier: release
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: pavankarnatigh
          autoAbortPreviousExecutions: true
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
          headerConditions: []
          actions: []
  pipelineBranchName: <+trigger.branch>
